// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace TicTacToe.iOS
{
	public partial class TutorialViewController : UIViewController
	{
		public TutorialViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			BackButton.TouchUpInside += (sender, e) => NavigationController.PopViewControllerAnimated(true);
		}
	}
}
