#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TicTacToe.Droid.Resource", IsApplication=true)]

namespace TicTacToe.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int trans_left_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int trans_left_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int trans_right_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int trans_right_out = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back_button_states = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int backPressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int blueO = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int blueX = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_colors = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int clear = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int clearPressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int greenO = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int greenX = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int grid = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int monoandroidsplash = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int new_game_states = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int newGame = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int newGamePressed = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int paperBackground = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int tictactoeLogo = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int BackButton = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int NewGameButton = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int PlayerOWinTextView = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int PlayerXWinTextView = 2131165190;
			
			// aapt resource value: 0x7f070012
			public const int StartGameButton = 2131165202;
			
			// aapt resource value: 0x7f070003
			public const int TitleTextView = 2131165187;
			
			// aapt resource value: 0x7f070011
			public const int TutorialButton = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int TutorialTextView = 2131165203;
			
			// aapt resource value: 0x7f070007
			public const int button1 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int button2 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int button3 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int button4 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int button5 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int button6 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int button7 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int button8 = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int button9 = 2131165199;
			
			// aapt resource value: 0x7f070004
			public const int footerBarLayout = 2131165188;
			
			// aapt resource value: 0x7f070010
			public const int logo = 2131165200;
			
			// aapt resource value: 0x7f070000
			public const int titleBarLayout = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Game = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Tutorial = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
