#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TicTacToe.Droid.Resource", IsApplication=true)]

namespace TicTacToe.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back_button_states = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int backPressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int blueO = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int blueX = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_colors = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int clear = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int clearPressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int greenO = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int greenX = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int grid = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int monoandroidsplash = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int new_game_states = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int newGame = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int newGamePressed = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int paperBackground = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int tictactoeLogo = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int BackButton = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int NewGameButton = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int PlayerOWinTextView = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int PlayerXWinTextView = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int StartGameButton = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int TitleTextView = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int TutorialButton = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int TutorialTextView = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int footerBarLayout = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int logo = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int titleBarLayout = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Game = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Tutorial = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
